### ISSUE TITLE
Rework "Add my site"

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-updater#100]
![image](https://user-images.githubusercontent.com/1123809/131891874-bbcdce66-2a6e-4158-8986-2b893ecaf93c.png)

* This dialog shouldn't discuss mediawiki at all. The user should just be prompted to enter their site name.
* The dialog should link to the update site request thread
* The `Real name`, `Email` and `password` fields should all be removed
* Lower case entries should be allowed, reverting https://github.com/imagej/imagej-updater/issues/40

**Comment by ctrueden** [comment]
As mentioned in #99, I already removed the "Add my site" button. In my opinion, this issue is moot because we shouldn't offer this feature at all.
