### ISSUE TITLE
Add update site with command line do not work

### ISSUE THREAD

**Issue by NicoKiaru** [imagej/imagej-updater#106]
As described in the [forum thread](https://forum.image.sc/t/fiji-add-update-site-headless-do-not-work/83673/2), add an update site through command line do not work anymore. The updater sends an error `[ERROR] Site 'QuickFigures' was already added!` even if the site was NOT added.

I wonder if that's an unintended consequence of the new GUI for the updater.

I do not know if it's the appropriate fix, but changing:

https://github.com/imagej/imagej-updater/blob/dd4b18af362bd46faae8820bb17d227817ad71f4/src/main/java/net/imagej/updater/CommandLine.java#L1276

to `final UpdateSite site = files.getUpdateSite(name, false);` fixes the issue.

OS: win 11, Fiji up to date on 14th July 2023 (ImageJ 2.14.0/1.5f Java 1.8.0_322 64 bits)

**Comment by imagejan** [comment]
@NicoKiaru wrote:
> `files.getUpdateSite(name, false);` fixes the issue.

Did you also test correct behavior if the update site indeed is active already? Or does that just suppress the error message?

**Comment by NicoKiaru** [comment]
Good point, yeah, I do not know what to test, so thanks for jumping in. I'll give it a shot.

Besides, I do not understand is how this could have worked before...

**Comment by NicoKiaru** [comment]
There's potentially the line 1277 and 1249 that need to be modified:
```
		final UpdateSite site = files.getUpdateSite(name, false);
```

But it does not really work in the end. After having executed:

```
./ImageJ-win64 --update add-update-site BAR http://sites.imagej.net/Tiago/
./ImageJ-win64 --ij2 --headless --update update
```

 I still need to go to the GUI and click apply:

![image](https://github.com/imagej/imagej-updater/assets/20223054/236e2301-b7a5-4bf3-851f-cc2604f7761b)

**Comment by imagejan** [comment]
I wonder if sciview is affected by this, as they use the updater in headless mode for their deployment:

https://github.com/scenerygraphics/sciview/blob/64fdc074d8886aae91f3ae3389ea3f1d8437c141/populate_fiji.sh#L76

/cc @kephale @ctrueden
