### ISSUE TITLE
As of Oct 9 2024, the Fiji updater generates an error and doesn't work

### ISSUE THREAD

**Issue by hyungsongnam** [imagej/imagej-updater#112]
Hello,
I'm not sure why but when I try to update the Fiji installation, I've been getting errors for the last few days.

![Screenshot 2024-10-09 at 2 13 36 PM](https://github.com/user-attachments/assets/37186c9e-30c7-40af-9d11-33807e7a83d2)

![Screenshot 2024-10-09 at 2 20 35 PM](https://github.com/user-attachments/assets/63a1744e-6469-4d18-aa01-691f64b2fb92)

On a different machine, I wiped the installation clean, but in that instance, I now don't see any of the other update sites.
Thanks.
Sincerely,
Hyung-song Nam, PhD

**Comment by ctrueden** [comment]
Hopefully fixed by imagej/list-of-update-sites@57c896747e9645ed5cc1b70ef6aecf9d53e791b0. See also fiji/fiji#358, which is the same issue cross-posted.
