### ISSUE TITLE
Auto-convert pacific.mpi-cbg.de to fiji.sc

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-updater#35]
The report at http://fiji.sc/bugzilla/show_bug.cgi?id=863 is the second in a very short amount of time that shows that there are *still* users whose Fiji update site points to `pacific.mpi-cbg.de`.

Now, the Max-Planck Institute of molecular Cell Biology and Genetics stopped supporting Fiji development and maintenance more than three years ago. So while it is true that `pacific` is still online, it basically just redirects to `fiji.sc`, gracefully hosted by [University of Wisconsin-Madison's Laboratory for Optical and Computational Instrumentation (LOCI)](http://loci.wisc.edu/).

It is clear by now that LOCI is a stable supporter of the ideas and community & techniques developed around ImageJ and Fiji, so let's auto-update the obsolete URLs with the `imagej-updater` whenever we detect one in the local configuration.

**Comment by ctrueden** [comment]
Solved (well enough) in 5cb22ded192ff155fc9084b12bf6203fa60592c5.
