### ISSUE TITLE
Unclear how to reconnect to / enter credentials for existing update site(s)

### ISSUE THREAD

**Issue by imagingbook** [imagej/imagej-updater#45]
I am trying to use the ImageJ updater in Advanced Mode to upload modified jar files to my existing update sites. Right-clicking on the modified local files gives me only these options:
- Keep as-is,
- Update,
- Uninstall.
No 'Upload to My Site' option anywhere (unlike described in the wiki). Similarly, the Manage Update Sites interface shows only buttons for 
- Add my site,
- Add,
- Remove,
- Close.
It seems totally unclear how to re-connect to any of 'my sites' or how to re-enter my credetials. At least this is too hard (impossible) to find for a casual user. Will warmly welcome improvements.

Thanks,
Wilhelm

**Comment by hinerm** [comment]
Hi Wilhelm,

>It seems totally unclear how to re-connect to any of 'my sites' or how to
re-enter my credetials.

You're absolutely right - that section had an unstated assumption you
recently went through the "Add your personal update site" section, and thus
has your wiki credentials set.

>Right-clicking on the modified local files gives me only these options

In addition to needing to specify your wiki account, the "Upload to ..."
option will only be available if there are no other pending changes. This
also was not mentioned in the guide.

I revised the wiki[1] to address both of these defects. Please give it a
look and let me know if anything else is missing or confusing!

Thank you for the valuable feedback.

Best,
Mark

[1]
http://imagej.net/How_to_set_up_and_populate_an_update_site#Uploading_files_to_your_update_site

**Comment by imagingbook** [comment]
Hello Mark,

thanks for attending to this. I must have missed the instructions for inserting the user name in the Host(!) column in 'Manage Update Sites'. This at least seemed to work now.

I could successfully mark 1 file for upload, while the other 3 were refused.
When I tried to apply the changes, I repetitively was asked for my login credentials for the same site, which I typed in bravely several times. Since it did not tell me what was wrong but just kept repeating, I gave up eventually.

Any clue? My wiki account name is "Imagingbook" - so I entered "webdav:Imagingbook"  in the "Host" column. Correct?

Actually, I would like to mark the existing jar files in sites
ImagingBookEn1
ImagingBookEn2
ImagingBookDe2
ImagingBookDe3
as obsolete, since the file names had to be changed (underscore needed for ImageJ1).

I know I am close, but it is really quite frustrating...

-Wilhelm


________________________________

**Comment by ctrueden** [comment]
> I repetitively was asked for my login credentials for the same site

Then your credentials (probably password) did not match.

See:
* http://imagej.net/Update_Sites#How_do_I_set_a_password_for_my_personal_update_site.3F
* http://imagej.net/Special:ChangeUploadPassword

**Comment by imagingbook** [comment]
I am logged in properly with exactly these credentials at http://imagej.net/Fiji, i.e., as user 'Imagingbook' plus my password. I was able to set/change the password but I still can't upload to my update site 'ImagingBookEn1' (e.g.) from within Fiji.

-Wilhelm


________________________________

**Comment by hinerm** [comment]
Hi @imagingbook

> Since it did not tell me what was wrong but just kept repeating, I gave up eventually.

It would definitely be nice to have an appropriate failure message here.. I [opened a new issue](https://github.com/imagej/imagej-ui-swing/issues/37) to add one.

> My wiki account name is "Imagingbook" - so I entered "webdav:Imagingbook" in the "Host" column. Correct?

This looks good. However, I looked over the users list, and it looks like the following users exist:
* ImagingBook
* ImagingBookEn1
* ImagingBookEn2
* ImagingBookDe2
* ImagingBookDe3

I have to dig a bit more to confirm, but I suspect that a unique wiki account was created for each of your update sites. So when you're asked to authenticate uploads to one of these sites, try using the corresponding account name (and ensure you have the correct update site password for that account of course).

>I am logged in properly with exactly these credentials at http://imagej.net/Fiji
>I was able to set/change the password

Sorry if this is obvious - but when using the [password change page](http://imagej.net/Special:ChangeUploadPassword) to update or initialize a password, make sure the "Your personal update site" radio button is checked. By default, "Fiji's main update site" is checked - which is just for uploading to core Fiji.

**Comment by imagingbook** [comment]
Hello Mark,

thanks for looking into this. I was not aware of the fact that each update site was associated with a separate user account. What I did not was the following:

1) At the password change page, I entered an upload password for ImagingBookEn1 (not for the others!). However, there was no radio button "Your personal update site" anywhere. Btw, could ANYBODY set this password (it did not ask for any credentials)???

2) In Fiji/"Manage Update Sites" I modified the corresponding names (e.g., webdav:ImagingBookEn1) in the 'Host' column.

3) I was able to successfully upload a new set of jar files to my 4 plugin sites ImagingBookEn1 ... ImagingBookDe3. I was asked (after entering the password once) once more for the associated host/password.

4) What I COULD NOT DO was to mark the old files as OBSOLETE! This option showed when I touched the menu first, but did not activate the "Apply changes" button. Subsequently this option was not available in the pull-down menu any more. Tried several times. This dialog appears to be broken.

I'd appreciate if you could help me with this last issue.

Thanks much,
Wilhelm



________________________________

**Comment by imagingbook** [comment]
Oups, should read "... What I did NOW was the following: .."

Wi

________________________________
From: Burger Wilhelm
Sent: Wednesday, April 01, 2015 09:23
To: imagej/imagej-updater; imagej/imagej-updater
Cc: Mark Hiner; Burger Wilhelm
Subject: RE: [imagej-updater] Unclear how to reconnect to / enter credentials for existing update site(s) (#45)

Hello Mark,

thanks for looking into this. I was not aware of the fact that each update site was associated with a separate user account. What I did not was the following:

1) At the password change page, I entered an upload password for ImagingBookEn1 (not for the others!). However, there was no radio button "Your personal update site" anywhere. Btw, could ANYBODY set this password (it did not ask for any credentials)???

2) In Fiji/"Manage Update Sites" I modified the corresponding names (e.g., webdav:ImagingBookEn1) in the 'Host' column.

3) I was able to successfully upload a new set of jar files to my 4 plugin sites ImagingBookEn1 ... ImagingBookDe3. I was asked (after entering the password once) once more for the associated host/password.

4) What I COULD NOT DO was to mark the old files as OBSOLETE! This option showed when I touched the menu first, but did not activate the "Apply changes" button. Subsequently this option was not available in the pull-down menu any more. Tried several times. This dialog appears to be broken.

I'd appreciate if you could help me with this last issue.

Thanks much,
Wilhelm



________________________________

**Comment by hinerm** [comment]
>I was not aware of the fact that each update site was associated with a separate user account

This isn't strictly the case.. it **is** possible to have an update site managed by a user with a different Wiki account. I am not 100% how to do this through the updater UI. What I expected to work - naming my update site what I wanted but using `webdav:Hinerm` in the host column - did not. I will look into this further and update the docs when I figure it out.

If you'd like, for now, I can manually add the Imagingbook user to each of your update site's authorized users. Let me know.

>However, there was no radio button "Your personal update site" anywhere

OH! It probably shows up dynamically based on the account's permissions. Very sorry for the confusion.

>Btw, could ANYBODY set this password (it did not ask for any credentials)???

http://imagej.net/Special:ChangeUploadPassword won't load unless you are an authenticated user. It didn't ask for credentials since you were already logged in to the wiki and it knew who you were.

>I was able to successfully upload a new set of jar files to my 4 plugin sites

Hooray!

>4) What I COULD NOT DO was to mark the old files as OBSOLETE!

Instructions for this were kind of unclear, and hidden on the FAQ of the Update Site Introduction page. I split the FAQ to its own page and [converted the instructions to a step-by-step procedure](http://imagej.net/Update_site_FAQ#How_do_I_remove_a_file_from_my_update_site.3F).

I went through the instructions myself once to make sure they're still up to date. If you don't mind, give them a try and let me know if you run into any problems.

Thanks again for the feedback - hopefully this whole process will be better for future users!

**Comment by imagingbook** [comment]
Hello Mark,

thanks for the additional clues. I can live with different user names (as long as I know them), thus no need to change.

The procedure you describe for marking files obsolete is pretty much what I have been trying all along. I just tried it once again follwing precisely your steps - the desired option simply does not show, regardless where I right-click or if I use the pull-down menu. I am attaching 3 screenshots so you can see what is happening.

Thanks,
-Wilhelm



________________________________

**Comment by hinerm** [comment]
@imagingbook - Thank you for testing these steps. There was indeed a step missing!

>the desired option simply does not show

Because there was a deleted file, it was marked "Install it." The updater can only go in one direction at a time (upload or download) so it wasn't letting you mark things for upload (by obsoleting them) while there was a pending download operation.

First you have to change everything to "Keep as-is" to get back to a neutral state with no pending downloads. Then you can mark things obsolete.

I updated the instructions to reflect this! Thanks again.

**Comment by imagingbook** [comment]
Well, I just followed what is stated in the instructions: "If the file is not hosted by any other active update site, delete it from your local installation." Perhaps you consider removing/modifying this sentence.

Nevertheless, I managed to remove all obsolete files now - thanks. I am used to complex things and I appreciate sophisticated features, but this was more than I would normally find bearable. I hope future users profit from this painful experience (assuming it not only happened to me)...

One more question: where does the updater get the information from that is shown in the file's "Details" box?

Thx & regards,
Wilhelm



________________________________

**Comment by ctrueden** [comment]
> I am used to complex things and I appreciate sophisticated features, but this was more than I would normally find bearable.

Sorry it was so painful. One issue is that you have several update sites with similar names, which complicates matters.

For what it's worth, I have now granted _all_ ImagingBook users permission to upload to _any_ ImagingBook update site. Those users/sites include:
* Imagingbook
* ImagingBook
* ImagingBookDe2
* ImagingBookDe3
* ImagingBookEn1
* ImagingBookEn2

So hopefully that gets you out of password hell, for the most part.

(As an aside: do you need both `Imagingbook` and `ImagingBook`? Or should one of those be deleted?)

> where does the updater get the information from that is shown in the file's "Details" box?

Two places:
1. From the JAR file's `pom.xml`, if present (i.e., if using Maven)
2. As specified by you—that is, the information is editable.

**Comment by ctrueden** [comment]
@hinerm wrote:
> Sorry if this is obvious - but when using the password change page to update or initialize a password, make sure the "Your personal update site" radio button is checked. By default, "Fiji's main update site" is checked - which is just for uploading to core Fiji.

Please note that the "Fiji's main update site" option is only available to those with upload permission to the Fiji update site. Otherwise, the form is just a password reset for the user's personal update site.

**Comment by ctrueden** [comment]
@imagingbook wrote via mail:
> > So hopefully that gets you out of password hell, for the most part.
> 
> Well, thanks to Mark I had come out of "password hell" already ;-)
> 
> > (As an aside: do you need both Imagingbook and ImagingBook? Or should
> > one of those be deleted?)
> 
> Yes, please remove the 'Imagingbook' site/user, it is obsolete (I didn't know it existed).

Done.

> > > where does the updater get the information from that is shown in the file's "Details" box?
> >
> > Two places:
> > 1. From the JAR file's pom.xml, if present (i.e., if using Maven)
> > 2. As specified by you—that is, the information is editable.
> 
> I don't use Maven. I tried to edit in the upload dialog but it did not let me change anything.
> Will test again with the next update.

Sounds good. It should work to make edits during any new version upload.

> The updater also had problems with non-existent dependencies in my plugin jars. They do not depend on each other but contain classes with identical names, although in different packages. Could this be the cause? I had to 'break dependencies' before the upload.

The Updater tries to autodetect your dependencies. But you can manually edit them in the right-hand box under the "Dependencies" section. Just remove the invalid ones.

Note, however, that the Updater's detection logic is quite robust, so if it detected a seemingly-wrong dependency, it is probably due to the same classes present in multiple JAR files. Are you using an uber-JAR (i.e., a JAR with embedded dependencies)? If so, I would [recommend against it](http://imagej.net/Uber-JAR).

> ImageJ also is not "package-aware" as far as plugins go - it always complains about duplicate plugin names (apparently IJ tests for class names only), although they can coexist and execute flawlessly.

In general, ImageJ certainly can handle multiple classes with the same name in different packages. The duplicate plugin warnings, IIRC, are caused by plugins with the same _label_ in `plugins.config`, not duplicate class names.
