### ISSUE TITLE
Also scan ijm files in ./scripts directory

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-updater#60]
Currently, the updater doesn't pick up `.ijm` files in `./ImageJ.app/scripts`, but they *are* being shown in the menu (i.e. discovered by `org.scijava.script.ScriptFinder` ?!).

To make the behavior consistent, I suggest to either:
* add `ijm` to the list of allowed extensions in `./scripts` here:
https://github.com/imagej/imagej-updater/blob/660eb43ade5e3fa67699170e52eb498abadd5bb8/src/main/java/net/imagej/updater/Checksummer.java#L442
i.e. make IJ1 macros first-class script citizens; or
* avoid discovery of `ijm` files in `./scripts` (from the SciJava side)

I tend to favor the first option as the least surprising one. If that's alright, I can make the change, submit a PR and test it.

**Comment by ctrueden** [comment]
Thanks @imagejan. The change was so easy, I just went ahead and did it.

**Comment by ctrueden** [comment]
I favor use of `scripts/` as better (more intuitive, less confusing) than the old `plugins/Scripts/` folder for scripts (including ImageJ macros). But all the existing scripts shipped with Fiji have not yet moved over. I can't think of a good reason not to simply move them all... except maybe that we should start wrapping them up into individual JAR files with proper metadata in POMs, similar to what we did with https://github.com/fiji/Correct_3D_Drift.
