### ISSUE TITLE
Offer a smart filter in the Manage Update Sites dialog

### ISSUE THREAD

**Issue by acardona** [imagej/imagej-updater#62]
It is kind of hard to discover which update sites provide which plugins or which java classes from a e.g. library. A search at the top of the table for Update Sites could filter the contents of the table to only those update sites with matching text, which ideally would be the name of the plugin or the name of a java class included in the update site jars.

Unzipping jar files in memory, or rather, listing their contents, to extract class names that contain an underscore, is doable. I'd extract all non-anonymous class file names anyway for filtering, so that libraries could be inspected in the same way. An iterative piece of code to do this is not hard (I've written one: 65 lines long in java [about 15 near the top are the relevant code], https://github.com/trakem2/TrakEM2/blob/master/TrakEM2_/src/main/java/ini/trakem2/Project.java#L129 ). Adapting mine or creating a new one would not be much work.

**Comment by ctrueden** [comment]
I agree this would be nice. No time this year, though. Feel free to file a PR in the meantime.

**Comment by ctrueden** [comment]
Also, note that the relevant repository for this work would be https://github.com/imagej/imagej-ui-swing.
