### ISSUE TITLE
Adding a custom update site fails if it uses https

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej-updater#82]
Hi @frauzufall ,

I just tried to add my favorite update site to Fiji (by clicking `Add Update Site` and entering it) and it failed with this error message as long as I tried to add the address with https ... 
![image](https://user-images.githubusercontent.com/12660498/67318938-80c02700-f50c-11e9-8031-2ea9b3c234bc.png)

With http it worked...

To me that appears like a https related bug...

Let me know if I can help tracing it down ;-)

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
... might be related to a server issue on imagej.net ... It doesn't respond sometimes today...

**Comment by haesleinhuepf** [comment]
Ok. Wasn't able to reproduce it in another Fiji. Was a false alarm then because of server down. 

Thanks for reading ;-)

**Comment by ctrueden** [comment]
Sorry for server outages. I'll be working on that in coming days. I think the main thing is I need to put rules in place to temporarily ban IPs that are spamming the server with thousands of update requests (e.g. cluster jobs).
